### PR TITLE
Adds an untype method, allowing for an animated text untyping

### PR DESCRIPTION
**Pull request by mshick**
This adds `untype`, as well as `toggleType` to prevent code repetition.

### CODE REVIEW

**Comment by gabrielflorit** [comment]
This looks good @mshick . How about `delete` instead of `untype`?

**Comment by mshick** [comment]
I'd argue the `delete` is a fairly loaded word and might confuse people. If you don't want to use `untype` I'd favor a word like `clear` maybe.

**Comment by gabrielflorit** [comment]
Good point. `clear` is also loaded. `untype` it is.

**Comment by gabrielflorit** [comment]
Thanks! Will update distro / npm shortly.

**Comment by mshick** [comment]
Cool! Thanks for merging.

**Comment by gabrielflorit** [comment]
Updated [npm version](https://www.npmjs.com/package/typewriter-js) - we're at `1.0.0` now. Also updated the demo: http://gabrielflorit.github.io/typewriter-js/

**Pull request merged**
